
export const animeConstants = {
    //Anime by filter
    ANIMES_REQUEST: "FETCH_ANIMES_REQUEST",
    ANIMES_SUCCESS: "FETCH_ANIMES_SUCCESS",
    ANIMES_FAILURE: "FETCH_ANIMES_FAILURE",
    //Anime by category
    ANIMES_FILTER_REQUEST: "FETCH_ANIMES_FILTER_REQUEST",
    ANIMES_FILTER_SUCCESS: "FETCH_ANIMES_FILTER_SUCCESS",
    ANIMES_FILTER_FAILURE: "FETCH_ANIMES_FILTER_FAILURE",
    //Anime by category 
    ANIMES_CATEGORIES_REQUEST: "FETCH_ANIMES_CATEGORIES_REQUEST",
    ANIMES_CATEGORIES_SUCCESS: "FETCH_ANIMES_CATEGORIES_SUCCESS",
    ANIMES_CATEGORIES_FAILURE: "FETCH_ANIMES_CATEGORIES_FAILURE",
    //Anime by collection
    ANIMES_COLLECTIONS_REQUEST: "FETCH_ANIMES_COLLECTIONS_REQUEST",
    ANIMES_COLLECTIONS_SUCCESS: "FETCH_ANIMES_COLLECTIONS_SUCCESS",
    ANIMES_COLLECTIONS_FAILURE: "FETCH_ANIMES_COLLECTIONS_FAILURE"
}